2012-05-23 10:32:07,706 [   INFO] Forge tools running at version 3.3.0
2012-05-23 10:32:07,707 [  DEBUG] Forge build tools version: 3.3.0
2012-05-23 10:32:07,707 [  DEBUG] main: {"server": "https://trigger.io/api/"}
2012-05-23 10:32:07,709 [  DEBUG] GET https://trigger.io/api/version_check/3/3/0/
2012-05-23 10:32:08,283 [  DEBUG] checking API response for success or error
2012-05-23 10:32:08,284 [   INFO] Update result: you already have the latest tools
2012-05-23 10:32:08,837 [  ERROR] src/config.json is not valid JSON: Expecting , delimiter: line 31 column 24 (char 691)
2012-05-23 11:15:28,463 [   INFO] Forge tools running at version 3.3.0
2012-05-23 11:15:30,693 [  DEBUG] ignoring non-target directory __init__.py
2012-05-23 11:15:30,693 [  DEBUG] ignoring non-target directory config.json
2012-05-23 11:15:30,693 [  DEBUG] ignoring non-target directory lib
2012-05-23 11:15:30,693 [  DEBUG] ignoring non-target directory platform_version.txt
2012-05-23 11:15:30,693 [   INFO] enabled platforms: ['web']
2012-05-23 11:15:30,964 [  DEBUG] Forge build tools version: 3.3.0
2012-05-23 11:15:30,964 [  DEBUG] main: {"server": "https://trigger.io/api/"}
2012-05-23 11:15:30,980 [  DEBUG] GET https://trigger.io/api/auth/loggedin
2012-05-23 11:15:32,092 [  DEBUG] checking API response for success or error
2012-05-23 11:15:32,093 [  DEBUG] already authenticated via cookie - continuing
2012-05-23 11:15:32,093 [  DEBUG] POST https://trigger.io/api/track/
2012-05-23 11:15:32,229 [  DEBUG] checking API response for success or error
2012-05-23 11:15:32,229 [   INFO] <ForgeTask (web)> running...
2012-05-23 11:15:32,229 [   INFO] reading app code from /Users/fernandonava/Desktop/forge-tools/demo_app/src
2012-05-23 11:15:32,230 [   INFO] writing new app to /Users/fernandonava/Desktop/forge-tools/demo_app/development
2012-05-23 11:15:32,231 [  DEBUG] <ForgeTask (web)> script:
[('all', None, 'lint_javascript', None, None),
 ('all', None, 'check_local_config_schema', None, None),
 ('web', None, 'run_web', None, None)]
2012-05-23 11:15:32,231 [  DEBUG] running lint_javascript((), {})
2012-05-23 11:15:32,231 [   INFO] Checking JavaScript files...
2012-05-23 11:15:32,682 [   INFO] JavaScript check complete
2012-05-23 11:15:32,683 [  DEBUG] running check_local_config_schema((), {})
2012-05-23 11:15:32,683 [   INFO] Verifying your configuration settings...
2012-05-23 11:15:32,716 [   INFO] Configuration settings check complete
2012-05-23 11:15:32,716 [  DEBUG] running run_web((), {})
2012-05-23 11:15:32,716 [  DEBUG] Running: npm install
2012-05-23 11:15:32,916 [  ERROR] failed to run npm: do you have Node.js installed and on your path? while running run_web((), {})
2012-05-23 11:15:32,916 [  ERROR] failed to run npm: do you have Node.js installed and on your path?
2012-05-24 16:34:57,016 [   INFO] Forge tools running at version 3.3.0
2012-05-24 16:34:57,017 [  DEBUG] Forge build tools version: 3.3.0
2012-05-24 16:34:57,017 [  DEBUG] main: {"server": "https://trigger.io/api/"}
2012-05-24 16:34:57,018 [  DEBUG] GET https://trigger.io/api/version_check/3/3/0/
2012-05-24 16:34:58,575 [  DEBUG] checking API response for success or error
2012-05-24 16:34:58,575 [   INFO] Update result: you already have the latest tools
2012-05-24 16:34:58,768 [  DEBUG] configuration is identical to last run
2012-05-24 16:34:58,768 [  DEBUG] GET https://trigger.io/api/auth/loggedin
2012-05-24 16:34:58,904 [  DEBUG] checking API response for success or error
2012-05-24 16:34:58,904 [  DEBUG] already authenticated via cookie - continuing
2012-05-24 16:34:58,905 [  DEBUG] ignoring non-target directory __init__.py
2012-05-24 16:34:58,905 [  DEBUG] ignoring non-target directory config.json
2012-05-24 16:34:58,905 [  DEBUG] ignoring non-target directory lib
2012-05-24 16:34:58,905 [  DEBUG] ignoring non-target directory platform_version.txt
2012-05-24 16:34:58,905 [  DEBUG] GET https://trigger.io/api/app/e9f5a012a48111e1bb6b12313d1adcbe/should_rebuild
2012-05-24 16:34:59,087 [  DEBUG] checking API response for success or error
2012-05-24 16:34:59,088 [   INFO] configuration is unchanged: using existing templates
2012-05-24 16:34:59,191 [  DEBUG] ignoring non-target directory __init__.py
2012-05-24 16:34:59,192 [  DEBUG] ignoring non-target directory config.json
2012-05-24 16:34:59,192 [  DEBUG] ignoring non-target directory lib
2012-05-24 16:34:59,192 [  DEBUG] ignoring non-target directory platform_version.txt
2012-05-24 16:34:59,192 [   INFO] enabled platforms: ['android', 'chrome', 'ios', 'web']
2012-05-24 16:34:59,192 [  ERROR] Failed to parse command line arguments at ios
2012-05-24 17:06:21,211 [   INFO] Forge tools running at version 3.3.0
2012-05-24 17:06:21,211 [  DEBUG] Forge build tools version: 3.3.0
2012-05-24 17:06:21,211 [  DEBUG] main: {"server": "https://trigger.io/api/"}
2012-05-24 17:06:21,212 [  DEBUG] GET https://trigger.io/api/version_check/3/3/0/
2012-05-24 17:06:21,338 [  DEBUG] UNCAUGHT EXCEPTION: 
Traceback (most recent call last):
  File "/Users/fernandonava/desktop/forge-tools/forge/main.py", line 89, in decorated_with_handler
    function(*args, **kwargs)
  File "/Users/fernandonava/desktop/forge-tools/forge/main.py", line 328, in development_build
    remote.check_version()
  File "/Users/fernandonava/desktop/forge-tools/forge/remote.py", line 260, in check_version
    'version_check/{version}/'.format(version=forge.get_version().replace('.','/'))
  File "/Users/fernandonava/desktop/forge-tools/forge/remote.py", line 197, in _api_get
    resp = self.__get_or_post(absolute_url, *args, **kw)
  File "/Users/fernandonava/desktop/forge-tools/forge/remote.py", line 165, in __get_or_post
    resp = getattr(self.session, method.lower())(url, *args, **kw)
  File "/Users/fernandonava/desktop/forge-tools/forge-dependencies/requests/sessions.py", line 225, in get
    return self.request('get', url, **kwargs)
  File "/Users/fernandonava/desktop/forge-tools/forge-dependencies/requests/sessions.py", line 208, in request
    r.send(prefetch=prefetch)
  File "/Users/fernandonava/desktop/forge-tools/forge-dependencies/requests/models.py", line 580, in send
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='trigger.io', port=443): Max retries exceeded with url: /api/version_check/3/3/0/
2012-05-24 17:06:21,338 [  ERROR] Something went wrong that we didn't expect:
2012-05-24 17:06:21,338 [  ERROR] HTTPSConnectionPool(host='trigger.io', port=443): Max retries exceeded with url: /api/version_check/3/3/0/
2012-05-24 17:06:21,338 [  ERROR] See /Users/fernandonava/Desktop/forge-tools/demo_app/forge-error.log for more details
2012-05-24 17:06:21,338 [  ERROR] Please contact support@trigger.io
2012-05-24 17:07:24,900 [   INFO] Forge tools running at version 3.3.0
2012-05-24 17:07:24,901 [  DEBUG] Forge build tools version: 3.3.0
2012-05-24 17:07:24,901 [  DEBUG] main: {"server": "https://trigger.io/api/"}
2012-05-24 17:07:24,902 [  DEBUG] GET https://trigger.io/api/version_check/3/3/0/
2012-05-24 17:07:24,916 [  DEBUG] UNCAUGHT EXCEPTION: 
Traceback (most recent call last):
  File "/Users/fernandonava/desktop/forge-tools/forge/main.py", line 89, in decorated_with_handler
    function(*args, **kwargs)
  File "/Users/fernandonava/desktop/forge-tools/forge/main.py", line 328, in development_build
    remote.check_version()
  File "/Users/fernandonava/desktop/forge-tools/forge/remote.py", line 260, in check_version
    'version_check/{version}/'.format(version=forge.get_version().replace('.','/'))
  File "/Users/fernandonava/desktop/forge-tools/forge/remote.py", line 197, in _api_get
    resp = self.__get_or_post(absolute_url, *args, **kw)
  File "/Users/fernandonava/desktop/forge-tools/forge/remote.py", line 165, in __get_or_post
    resp = getattr(self.session, method.lower())(url, *args, **kw)
  File "/Users/fernandonava/desktop/forge-tools/forge-dependencies/requests/sessions.py", line 225, in get
    return self.request('get', url, **kwargs)
  File "/Users/fernandonava/desktop/forge-tools/forge-dependencies/requests/sessions.py", line 208, in request
    r.send(prefetch=prefetch)
  File "/Users/fernandonava/desktop/forge-tools/forge-dependencies/requests/models.py", line 580, in send
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='trigger.io', port=443): Max retries exceeded with url: /api/version_check/3/3/0/
2012-05-24 17:07:24,916 [  ERROR] Something went wrong that we didn't expect:
2012-05-24 17:07:24,916 [  ERROR] HTTPSConnectionPool(host='trigger.io', port=443): Max retries exceeded with url: /api/version_check/3/3/0/
2012-05-24 17:07:24,916 [  ERROR] See /Users/fernandonava/Desktop/forge-tools/demo_app/forge-error.log for more details
2012-05-24 17:07:24,916 [  ERROR] Please contact support@trigger.io
